# Generated by Django 4.2.5 on 2023-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_computer_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('Mac OS', 'Mac OS'), ('Windows 11', 'Windows 11'), ('Windows 10', 'Windows 10'), ('Windows 8', 'Windows 8'), ('Linux', 'Linux')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase mm-dd-yy'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='users_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
