# Generated by Django 4.2.5 on 2023-09-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_operating_system_alter_computer_operating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.ManyToManyField(blank=True, to='djangoapp.operating_system'),
        ),
    ]
