# Generated by Django 4.2.5 on 2023-09-20 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_computerhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerhistory',
            name='operating_system',
        ),
        migrations.AlterField(
            model_name='computerhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computerhistory',
            name='operating_system',
            field=models.ManyToManyField(blank=True, to='djangoapp.operating_system'),
        ),
    ]
